services:
  client:
    image: ghcr.io/jcares/pcc-tunnel-client:latest
    restart: unless-stopped
    environment:
      PCC_SERVER_URL: CHANGE_ME_SERVER_URL
      PCC_AUTH_TOKEN: CHANGE_ME_TOKEN
      PCC_REGISTRATION_KEY: CHANGE_ME_REGISTRATION_KEY
      PCC_PROXY_LOCAL: http://host.docker.internal:80
    volumes:
      - ./client/config:/app/config:ro
      - ./client/logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
